"""Markdown catalog for ``colleague explain <path>``.

Each entry is verbatim markdown. Keys are command-path tuples. The empty tuple
and ``("colleague",)`` both resolve to the root entry.

Keep bodies self-contained: an agent reading one entry should get enough
context without chaining reads.
"""

from __future__ import annotations

from colleague.explain.catalog_advanced import (
    _MCP,
    _PLAN,
    _PROMOTE,
)
from colleague.explain.catalog_core import (
    _CLEAN,
    _CLI,
    _DOCTOR,
    _EXPLAIN,
    _LEARN,
    _LEARN_FROM,
    _LIVECHECK,
    _OVERVIEW,
    _QUICKSTART,
    _ROOT,
    _WHOAMI,
)
from colleague.explain.catalog_ops import (
    _ASK_COLLEAGUE,
    _CONFIG,
    _EXPERIMENT,
    _FLIGHT,
    _STRIVE,
    _SUBAGENT,
    _TALK,
    _TUI,
)
from colleague.explain.catalog_organs import (
    _COHERENCE,
    _FEEDBACK,
    _LOBES,
    _ORGANS,
    _TELEMETRY,
)
from colleague.explain.catalog_work import (
    _AGENTS,
    _APPROVE,
    _BACKENDS,
    _COMMANDS,
    _HOOKS,
    _ROLES,
    _SESSION,
    _SKILLS,
    _WORK,
)

ENTRIES: dict[tuple[str, ...], str] = {
    (): _ROOT,
    ("colleague",): _ROOT,
    ("promote",): _PROMOTE,
    ("work",): _WORK,
    ("drive",): _WORK,  # deprecated alias — explain still resolves the old name
    ("session",): _SESSION,
    ("backends",): _BACKENDS,
    ("backends", "list"): _BACKENDS,
    ("backends", "overview"): _BACKENDS,
    ("wheels",): _BACKENDS,  # deprecated alias — explain still resolves the old name
    ("wheels", "list"): _BACKENDS,
    ("wheels", "overview"): _BACKENDS,
    ("whoami",): _WHOAMI,
    ("quickstart",): _QUICKSTART,
    ("learn",): _LEARN,
    ("explain",): _EXPLAIN,
    ("overview",): _OVERVIEW,
    ("doctor",): _DOCTOR,
    ("livecheck",): _LIVECHECK,
    ("clean",): _CLEAN,
    ("learn-from",): _LEARN_FROM,
    ("cli",): _CLI,
    ("cli", "overview"): _CLI,
    ("commands",): _COMMANDS,
    ("commands", "list"): _COMMANDS,
    ("commands", "overview"): _COMMANDS,
    ("commands", "approve"): _APPROVE,
    ("hooks",): _HOOKS,
    ("hooks", "list"): _HOOKS,
    ("hooks", "overview"): _HOOKS,
    ("hooks", "approve"): _APPROVE,
    ("agents",): _AGENTS,
    ("agents", "list"): _AGENTS,
    ("agents", "overview"): _AGENTS,
    ("skills",): _SKILLS,
    ("skills", "list"): _SKILLS,
    ("skills", "overview"): _SKILLS,
    ("roles",): _ROLES,
    ("roles", "list"): _ROLES,
    ("roles", "overview"): _ROLES,
    ("approve",): _APPROVE,
    ("feedback",): _FEEDBACK,
    ("feedback", "record"): _FEEDBACK,
    ("feedback", "show"): _FEEDBACK,
    ("feedback", "list"): _FEEDBACK,
    ("feedback", "overview"): _FEEDBACK,
    ("telemetry",): _TELEMETRY,
    ("telemetry", "status"): _TELEMETRY,
    ("telemetry", "overview"): _TELEMETRY,
    ("lobes",): _LOBES,
    ("lobes", "show"): _LOBES,
    ("lobes", "overview"): _LOBES,
    ("organs",): _ORGANS,
    ("organs", "list"): _ORGANS,
    ("organs", "overview"): _ORGANS,
    ("coherence",): _COHERENCE,
    ("coherence", "overview"): _COHERENCE,
    ("coherence", "score"): _COHERENCE,
    ("coherence", "show"): _COHERENCE,
    ("config",): _CONFIG,
    ("config", "show"): _CONFIG,
    ("config", "overview"): _CONFIG,
    ("subagent",): _SUBAGENT,
    ("subagents",): _SUBAGENT,
    ("ask-colleague",): _ASK_COLLEAGUE,
    ("outsource",): _ASK_COLLEAGUE,  # deprecated alias — explain still resolves the old name
    ("tui",): _TUI,
    ("tui", "render"): _TUI,
    ("tui", "state"): _TUI,
    ("tui", "inspect"): _TUI,
    ("tui", "action"): _TUI,
    ("tui", "replay"): _TUI,
    ("tui", "snapshot"): _TUI,
    ("tui", "test"): _TUI,
    ("tui", "diagnose"): _TUI,
    ("tui", "overview"): _TUI,
    ("flight",): _FLIGHT,
    ("flight", "status"): _FLIGHT,
    ("flight", "guide"): _FLIGHT,
    ("flight", "stop"): _FLIGHT,
    ("flight", "list"): _FLIGHT,
    ("flight", "overview"): _FLIGHT,
    ("strive",): _STRIVE,
    ("strive", "run"): _STRIVE,
    ("strive", "overview"): _STRIVE,
    ("experiment",): _EXPERIMENT,
    ("experiment", "start"): _EXPERIMENT,
    ("experiment", "status"): _EXPERIMENT,
    ("experiment", "list"): _EXPERIMENT,
    ("experiment", "summarize"): _EXPERIMENT,
    ("experiment", "overview"): _EXPERIMENT,
    ("talk",): _TALK,
    ("plan",): _PLAN,
    ("plan", "run"): _PLAN,
    ("plan", "continue"): _PLAN,
    ("plan", "status"): _PLAN,
    ("plan", "overview"): _PLAN,
    ("mcp",): _MCP,
    ("mcp", "serve"): _MCP,
    ("mcp", "overview"): _MCP,
}
